name: Deploy Storybook

on:
  push:
    branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build storybook static files
        run: npm run build-storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/.storybook-static

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GH Pages Bot"
          git config user.email "hello@ghbot.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          cd /out/.storybook-out
          git add .
          git commit -am "Deploy Storybook to GitHub Pages"
          cd ../..
          git subtree split --prefix web/storybook-out -b gh-pages
          git push -f origin gh-pages:gh-pages
